workflows:
    test-inputs:
        inputs:
            foo:
                description: Select app
                type: choice
                default: op1
                options:
                    - op1
                    - op2
        scripts:
            - name: show input
              script: echo ${{ inputs.foo }}
